# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from spire.api.server.debug.v1 import debug_pb2 as spire_dot_api_dot_server_dot_debug_dot_v1_dot_debug__pb2


class DebugStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/spire.api.server.debug.v1.Debug/GetInfo',
                request_serializer=spire_dot_api_dot_server_dot_debug_dot_v1_dot_debug__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=spire_dot_api_dot_server_dot_debug_dot_v1_dot_debug__pb2.GetInfoResponse.FromString,
                )


class DebugServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """Get information about SPIRE server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DebugServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=spire_dot_api_dot_server_dot_debug_dot_v1_dot_debug__pb2.GetInfoRequest.FromString,
                    response_serializer=spire_dot_api_dot_server_dot_debug_dot_v1_dot_debug__pb2.GetInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spire.api.server.debug.v1.Debug', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Debug(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/spire.api.server.debug.v1.Debug/GetInfo',
            spire_dot_api_dot_server_dot_debug_dot_v1_dot_debug__pb2.GetInfoRequest.SerializeToString,
            spire_dot_api_dot_server_dot_debug_dot_v1_dot_debug__pb2.GetInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
